# Generated by Django 4.0.10 on 2024-07-31 08:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ee_customers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerOTP',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('customer_otp_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('otp', models.CharField(max_length=255)),
                ('customer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ee_customers.customers')),
            ],
            options={
                'db_table': 'ee_customer_otp',
            },
        ),
    ]
